apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gsprestapi.fullname" . }}
  labels:
{{ include "gsprestapi.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gsprestapi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "gsprestapi.name" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "GOOGLE_ANALYTICS_ID"
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_ANALYTICS_ID
                  name: google_analytics_auth
            - name: "GOOGLE_ANALYTICS_TOKEN"
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_ANALYTICS_TOKEN
                  name: google_analytics_auth

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: Host
                  value: localhost
            timeoutSeconds: 15
            initialDelaySeconds: 300
          readinessProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: Host
                  value: localhost
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /mnt
              name: geoglows-data-volume
      volumes:
        - name: geoglows-data-volume
          persistentVolumeClaim:
            claimName: nfs-geoglows-prod-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
