apiVersion: v1
kind: Secret
metadata:
  name: aws-auth
data:
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY | b64enc }}
  AWS_REGION: {{ .Values.AWS_REGION | b64enc }}
  AWS_LOG_GROUP_NAME: {{ .Values.AWS_LOG_GROUP_NAME | b64enc }}
  AWS_LOG_STREAM_NAME: {{ .Values.AWS_LOG_STREAM_NAME | b64enc }}
