# Default values for gsprestapi.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "docker.aquaveo.com/geoglows/gsp_rest_api"
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab-registry
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

  tls: []

resources: 
  requests:
    cpu: 1
    memory: 512Mi
  limits:
    cpu: 4
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
